version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1

volumes:
  postgres_data:
