# Generated by Django 4.0 on 2025-04-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_name', models.CharField(max_length=200, unique=True, verbose_name='Version Name')),
                ('role_name', models.CharField(choices=[('TL', 'Team Lead'), ('MB', 'Member')], default='MB', help_text='Role that this criteria tree version is implemented to', max_length=2, verbose_name='Role name')),
                ('state', models.CharField(choices=[('Unofficial', 'Unofficial'), ('Official', 'Official'), ('Outdated', 'Outdated')], default='Unofficial', help_text='Criteria tree version state', max_length=32)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='users.customuser')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='users.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input type name', max_length=20, unique=True)),
                ('min', models.IntegerField(blank=True, help_text='Minimum value of the input type (if this is None => negative infinity)', null=True)),
                ('max', models.IntegerField(blank=True, help_text='Maximum value of the input type (if this is None => positive infinity)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultPolicy',
            fields=[
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='criteria.criteriaversion')),
                ('grading_rule', models.JSONField(help_text='Define perfomance point to grade mapping', verbose_name='Grading rule')),
                ('action_grades', models.JSONField(help_text='Grades need to take action', verbose_name='Action grades')),
                ('explanation_grades', models.JSONField(help_text='Grades need to be explained', verbose_name='Explanation grades')),
            ],
            options={
                'verbose_name_plural': 'Result policies',
            },
        ),
        migrations.CreateModel(
            name='VariableRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_alias', models.CharField(help_text='Select the variable (alias) that this relationship depends on', max_length=20, verbose_name='From')),
                ('to_alias', models.CharField(help_text='Select the variable (alias) that depends on this relationship', max_length=20, verbose_name='To')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.criteriaversion')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('alias', models.CharField(help_text='Alias for this criteria (used for creating expression)', max_length=20)),
                ('parent_alias', models.CharField(blank=True, help_text='Parent criteria alias of this criteria (null if this criteria has no parent)', max_length=20, null=True, verbose_name='Parent alias')),
                ('description', models.TextField(blank=True, help_text='A description for this criteria', null=True)),
                ('is_input', models.BooleanField(default=False, help_text='Is this criteria an input criteria (if this true, it will not be counted in the evaluation calculating)', verbose_name='Is input')),
                ('expression', models.CharField(blank=True, help_text='The expression to calculate evaluation point', max_length=200, null=True)),
                ('is_final_result', models.BooleanField(default=False, help_text='Criteria will be used to get the final result', verbose_name='Is final result')),
                ('input_type', models.ForeignKey(blank=True, help_text='Type of Input value (% or #), if this is None, using the default value type (negative infinity to positive infinity)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='criteria.inputtype', verbose_name='Input type')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.criteriaversion')),
            ],
            options={
                'verbose_name_plural': 'Criteria',
            },
        ),
    ]
