# Generated by Django 4.0 on 2025-03-18 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('init_password', models.CharField(blank=True, max_length=10, null=True, verbose_name='initial password')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('question', models.TextField(blank=True, null=True, verbose_name='question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='answer')),
                ('is_default_password', models.BooleanField(default=True, verbose_name='is default password?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=20, verbose_name='access level')),
                ('can_read_eval_data', models.BooleanField(default=True, verbose_name='can read evaluation data')),
                ('can_write_eval_data', models.BooleanField(default=False, verbose_name='can write evaluation data')),
                ('can_read_eval_settings', models.BooleanField(default=False, verbose_name='can read evaluation settings')),
                ('can_write_eval_settings', models.BooleanField(default=False, verbose_name='can write evaluation settings')),
                ('can_read_criteria_settings', models.BooleanField(default=False, verbose_name='can read criteria settings')),
                ('can_write_criteria_settings', models.BooleanField(default=False, verbose_name='can write criteria settings')),
                ('can_export', models.BooleanField(default=False, verbose_name='can export')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('parent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.team', verbose_name='parent team')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PM', 'Project Manager'), ('SM', 'Scrum Master'), ('TL', 'Team Lead'), ('DEV', 'Developer'), ('TEST', 'Tester')], default='DEV', max_length=150, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuserpermission', verbose_name='access level')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team', verbose_name='team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='user')),
            ],
        ),
    ]
