# Generated by Django 4.0 on 2025-04-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuserpermission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Project Manager', 'PM'), ('Scrum Master', 'SM'), ('Team Lead', 'TL'), ('Developer', 'DEV'), ('Tester', 'TEST')], default='Developer', max_length=150, verbose_name='role'),
        ),
    ]
